# Generated by Django 2.2.12 on 2022-07-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lesson'),
        ('main_app', '0002_auto_20220718_2151'),
    ]

    operations = [
    ]
