# Generated by Django 4.0.6 on 2022-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
