# Generated by Django 4.0.6 on 2022-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_student_learning_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learning_difference',
            field=models.CharField(choices=[('n', 'No'), ('y', 'Yes')], default='n', max_length=2),
        ),
    ]
