# Generated by Django 2.2.12 on 2022-07-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_photo'),
        ('main_app', '0012_homework'),
    ]

    operations = [
    ]
