# Generated by Django 4.0.6 on 2022-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_course_id_alter_homework_id_alter_lesson_id_and_more'),
        ('main_app', '0014_auto_20220720_2224'),
    ]

    operations = [
    ]
